#  Домашнее задание

In [1]:
import numpy as np

### Задание  
#### 1. Создайте случайную матрицу А1 размерностью 5 на 5


In [7]:
np.random.seed(21)
A1 = np.random.randint(0, 9, size=(5, 5))
A1

array([[8, 4, 0, 0, 8],
       [3, 2, 1, 8, 6],
       [0, 4, 6, 4, 4],
       [7, 8, 5, 6, 5],
       [2, 6, 2, 8, 2]])

#### 2. Транспонируйте матрицу A1


In [60]:
# вариант 1 
A12 = A1.T
A12

array([[8, 3, 0, 7, 2],
       [4, 2, 4, 8, 6],
       [0, 1, 6, 5, 2],
       [0, 8, 4, 6, 8],
       [8, 6, 4, 5, 2]])

In [25]:
# вариант 2
np.transpose(A1)

array([[8, 3, 0, 7, 2],
       [4, 2, 4, 8, 6],
       [0, 1, 6, 5, 2],
       [0, 8, 4, 6, 8],
       [8, 6, 4, 5, 2]])

#### 3. Найдите обратную матрицу для А1

In [62]:
A13 = np.linalg.inv(A1)
A13

array([[-0.10680751,  0.09859155, -0.18075117,  0.28638498, -0.22300469],
       [ 0.16079812, -0.22535211,  0.07981221, -0.17840376,  0.31924883],
       [-0.1443662 ,  0.05633803,  0.06338028,  0.21126761, -0.24647887],
       [-0.09565728,  0.12676056, -0.0657277 ,  0.05868545, -0.0129108 ],
       [ 0.15140845,  0.01408451,  0.14084507, -0.1971831 ,  0.06338028]])

#### 4. Создайте диагональную матрицу - поэлементно перемножив единичную матрицу I и случайную матрицу A2 размерности 4 на 4

In [54]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [55]:
np.random.seed(21) 
A2 = np.random.randint(0, 9, size=(4, 4))
A2

array([[8, 4, 0, 0],
       [8, 3, 2, 1],
       [8, 6, 0, 4],
       [6, 4, 4, 7]])

In [56]:
A3 = np.multiply(I, A22)
A3

array([[5., 0., 0., 0.],
       [0., 7., 0., 0.],
       [0., 0., 2., 0.],
       [0., 0., 0., 7.]])

#### 5. Создайте нулевую матрицу размерности 3 на 3

In [57]:
A4 = np.zeros([3, 3])
A4

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 6. Для всех полученных матриц найдите: определитель, ранг и собственные значения

In [89]:
# определитель
d1 = np.linalg.det(A1)
d2 = np.linalg.det(A12)
d3 = np.linalg.det(A13)
d4 = np.linalg.det(A3)
d5 = np.linalg.det(A4)

print(f'Определитель случайной матрицы А1 = {d1}')
print(f'Определитель транспонируованной матрицы A1 = {d2}')
print(f'Определитель обратной матрицы А1 = {d3}')
print(f'Определитель диагональной матрицы А3 = {d4}')
print(f'Определитель нулевой матрицы А4 = {d5}')

Определитель случайной матрицы А1 = -6816.0000000000055
Определитель транспонируованной матрицы A1 = -6815.999999999994
Определитель обратной матрицы А1 = -0.00014671361502347432
Определитель диагональной матрицы А3 = 489.99999999999983
Определитель нулевой матрицы А4 = 0.0


In [73]:
# ранг

r1 = np.linalg.matrix_rank(A1)
r2 = np.linalg.matrix_rank(A12)
r3 = np.linalg.matrix_rank(A13)
r4 = np.linalg.matrix_rank(A3)
r5 = np.linalg.matrix_rank(A4)

print(f'Ранг случайной матрицы А1 = {r1}')
print(f'Ранг транспонируованной матрицы A1 = {r2}')
print(f'Ранг обратной матрицы А1 = {r3}')
print(f'Ранг диагональной матрицы А3 = {r4}')
print(f'Ранг нулевой матрицы А4 = {r5}')

Ранг случайной матрицы А1 = 5
Ранг транспонируованной матрицы A1 = 5
Ранг обратной матрицы А1 = 5
Ранг диагональной матрицы А3 = 4
Ранг нулевой матрицы А4 = 0


In [83]:
# собственные значения

np.linalg.eigvals(A1)

e1 = np.linalg.eigvals(A1)
e2 = np.linalg.eigvals(A12)
e3 = np.linalg.eigvals(A13)
e4 = np.linalg.eigvals(A3)
e5 = np.linalg.eigvals(A4)

print(f'Cобственные значения случайной матрицы А1: \n {e1}')
print(f'Cобственные значения транспонируованной матрицы A1: \n {e2}')
print(f'Cобственные значения обратной матрицы А1:  \n {e3}')
print(f'Cобственные значения диагональной матрицы А3: {e4}')
print(f'Cобственные значения нулевой матрицы А4: {e5}')

Cобственные значения случайной матрицы А1: 
 [22.45879511+0.j         6.66522971+0.j        -0.532376  +3.3066077j
 -0.532376  -3.3066077j -4.05927282+0.j       ]
Cобственные значения транспонируованной матрицы A1: 
 [22.45879511+0.j         6.66522971+0.j        -0.532376  +3.3066077j
 -0.532376  -3.3066077j -4.05927282+0.j       ]
Cобственные значения обратной матрицы А1:  
[-0.0474612 +0.29478332j -0.0474612 -0.29478332j  0.15003234+0.j
  0.04452599+0.j         -0.24634954+0.j        ]
Cобственные значения диагональной матрицы А3: [5. 7. 2. 7.]
Cобственные значения нулевой матрицы А4: [0. 0. 0.]


#### 7. Проанализируйте результаты

In [91]:
# 1. 
# Определитель матрицы не меняется при её транспонировании
# У нулевой матрицы определить всегда равен нулю.
# Определитель единичной матрицы равен 1.
# Определитель обратной матрицы равен обратной величине определителя исходной матрицы
d3 *d1

1.0000000000000018

In [ ]:
# 2.
# Ранг матрицы, полученной транспонированием, равен рангу исходной матрицы.
# Ранг нулевой матрицы равен нулю.
# A13 — квадратная матрица и определитель det A13=0, то строки и столбцы этой матрицы линейно зависимы.

In [ ]:
# 3.
# Собственные значения у диагональной матрицы равны значениям главной диагонали.
# Для нулевой матирицы собственные значения равны нулю.
# Собственные значения случайной и транспонированной матрицы идентичны.